### ISSUE TITLE
Add option to create custom sharer

### ISSUE THREAD

**Issue by D4rkMindz** [ntnyq/vuepress-plugin-social-share#15]
Hi there
I really like your plugin.
The only problem is, that i'd like to create a custom sharer for my website (very specific thing).
How about we create a NETWORK_DATA list, where the share link is created via a callback? This would enable you to create a custom sharer with even dynamic sharer options (e.g. executing a copy to clipboard function).

Reach out to me if you'd like to implement this with me

**Comment by ntnyq** [comment]
Thanks

Here is my plan:

Custom sharers will be supported via an option `extendsNetworks` of the plugin.

networksData to create sharers will be the result of `Object.assign({}, defaultNetworks, extendsNetworks)` so that user can overrides the defaultNetworks, too.

svg icon, network image or image in `.vuepress/public` will be supported to custom the sharer's icon.

**Comment by ntnyq** [comment]
Released in [v0.1.0](https://github.com/ntnyq/vuepress-plugin-social-share/tree/v0.1.0)

[Docs and demos](https://sns.goyfe.com/)
